apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-demo-api.fullname" . }}
  labels:
    {{- include "gitops-demo-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "gitops-demo-api.name" . }}
