replicaCount: 2

image:
  repository: 43.205.115.210/library/gitops-demo-api
  pullPolicy: Always
  tag: "3aeccbd76dc69335b5b450224309a2b33fa8819b"

service:
  type: NodePort
  port: 3000
  nodePort: 31000

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

env:
  APP_VERSION: "1.0.0"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
