replicaCount: 3

image:
  repository: 43.205.115.210/library/gitops-demo-api
  pullPolicy: Always
  tag: "f6d31d5cf0a5f6f0e2394b0b761b900a3d735969"

service:
  type: NodePort
  port: 3000
  nodePort: 31000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

env:
  APP_VERSION: "2.0.0"
  NODE_ENV: "production"

# Name of existing Secret that holds REDIS_URL key
redis:
  secretName: "redis-secret"
  secretKey: "REDIS_URL"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
